/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModelBeans.FuncionarioBeans;
import ModelBeans.ModeloTabela;
import ModelConexao.ConexaoBD;
import ModelDao.FuncionarioDao;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Aurelio Macie Junior
 */
public class CadastroDeFuncionarios extends javax.swing.JFrame {

    FuncionarioBeans mod = new FuncionarioBeans();
    ModelDao.FuncionarioDao control = new FuncionarioDao();
    FuncionarioDao dao = new FuncionarioDao();
    ConexaoBD conex = new ConexaoBD();
    int flag = 0;
    
    public CadastroDeFuncionarios() {
        initComponents();
        preencherTabela("select * from funcionario order by id");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNomeFuncionario = new javax.swing.JTextField();
        jTextFieldContactoFuncionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jComboBoxSexoFuncionario = new javax.swing.JComboBox<>();
        jComboBoxEstadoCivilFuncionario = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNrDeIdentificacao = new javax.swing.JTextField();
        jButtonFecharCadastroFuncionario = new javax.swing.JButton();
        jTextFieldNascimentoFuncionario = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jTextFieldId = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFuncionarios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 270, 700, 140);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 60, 30, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Formulário  De Cadastro De Funcionário");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 380, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 100, 70, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contacto");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 144, 80, 30);

        jTextFieldNomeFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldNomeFuncionario.setEnabled(false);
        getContentPane().add(jTextFieldNomeFuncionario);
        jTextFieldNomeFuncionario.setBounds(150, 100, 260, 30);

        jTextFieldContactoFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldContactoFuncionario.setEnabled(false);
        getContentPane().add(jTextFieldContactoFuncionario);
        jTextFieldContactoFuncionario.setBounds(150, 140, 260, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sexo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 190, 60, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estado Civil");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(460, 100, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nascimento");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 190, 90, 30);

        jTextFieldPesquisar.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(490, 0, 260, 30);

        jComboBoxSexoFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxSexoFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jComboBoxSexoFuncionario.setEnabled(false);
        jComboBoxSexoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexoFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxSexoFuncionario);
        jComboBoxSexoFuncionario.setBounds(110, 190, 50, 30);

        jComboBoxEstadoCivilFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxEstadoCivilFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Viúvo(a)", "Divorciado(a)" }));
        jComboBoxEstadoCivilFuncionario.setEnabled(false);
        getContentPane().add(jComboBoxEstadoCivilFuncionario);
        jComboBoxEstadoCivilFuncionario.setBounds(560, 100, 200, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("N° De Identificacao");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(460, 140, 140, 30);

        jTextFieldNrDeIdentificacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldNrDeIdentificacao.setEnabled(false);
        getContentPane().add(jTextFieldNrDeIdentificacao);
        jTextFieldNrDeIdentificacao.setBounds(600, 140, 160, 30);

        jButtonFecharCadastroFuncionario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonFecharCadastroFuncionario.setText("X");
        jButtonFecharCadastroFuncionario.setToolTipText("Fechar Cadastro De Funcionário");
        jButtonFecharCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharCadastroFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFecharCadastroFuncionario);
        jButtonFecharCadastroFuncionario.setBounds(760, 0, 40, 30);

        jTextFieldNascimentoFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldNascimentoFuncionario.setEnabled(false);
        getContentPane().add(jTextFieldNascimentoFuncionario);
        jTextFieldNascimentoFuncionario.setBounds(300, 190, 70, 30);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(150, 240, 80, 25);

        jTextFieldId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldId.setEnabled(false);
        getContentPane().add(jTextFieldId);
        jTextFieldId.setBounds(90, 60, 40, 30);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(450, 240, 90, 25);

        jButtonPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/search_24px.png"))); // NOI18N
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(460, 0, 30, 30);

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.setToolTipText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(60, 240, 70, 25);

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(250, 240, 80, 25);

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(350, 240, 80, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/FundoParaTodasTelasRegistro.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 420);

        jButton5.setText("jButton5");
        getContentPane().add(jButton5);
        jButton5.setBounds(330, 240, 73, 23);

        jButton7.setText("jButton7");
        getContentPane().add(jButton7);
        jButton7.setBounds(520, 220, 73, 23);

        setSize(new java.awt.Dimension(815, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSexoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexoFuncionarioActionPerformed

    private void jButtonFecharCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharCadastroFuncionarioActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharCadastroFuncionarioActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        jTextFieldPesquisar.setText("");
        if (jTextFieldNomeFuncionario.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Nome' Para Continuar!");
           jTextFieldNomeFuncionario.requestFocus();
       }else if(jTextFieldContactoFuncionario.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Contacto' Para Continuar!");
           jTextFieldContactoFuncionario.requestFocus();
       }else if(jTextFieldNascimentoFuncionario.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Nascimento' Para Continuar!");
           jTextFieldNascimentoFuncionario.requestFocus();
       }else if(jTextFieldNrDeIdentificacao.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Número De Identificação' Para Continuar!");
           jTextFieldNrDeIdentificacao.requestFocus();
       }else if(jTextFieldNrDeIdentificacao.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Hora De Entrega' Para Continuar!");
           jTextFieldNrDeIdentificacao.requestFocus();
           
       } else if (flag==1){ 
       
        mod.setNome(jTextFieldNomeFuncionario.getText());
        mod.setContacto(jTextFieldContactoFuncionario.getText());
        mod.setSexo((String)jComboBoxSexoFuncionario.getSelectedItem());
        mod.setNascimento(Integer.valueOf(jTextFieldNascimentoFuncionario.getText()));
        mod.setEstadoCivil((String)jComboBoxEstadoCivilFuncionario.getSelectedItem());
        mod.setNrDeIdentificacao(jTextFieldNrDeIdentificacao.getText());
        control.salvar(mod);  
            
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        
        jTextFieldNomeFuncionario.setText("");
        jTextFieldContactoFuncionario.setText("");
        jTextFieldNascimentoFuncionario.setText("");
        jTextFieldNrDeIdentificacao.setText("");
        jTextFieldId.setText("");
        
        jComboBoxEstadoCivilFuncionario.setEnabled(!true);
        jComboBoxSexoFuncionario.setEnabled(!true);
        jTextFieldContactoFuncionario.setEnabled(!true);
        jTextFieldNascimentoFuncionario.setEnabled(!true);
        jTextFieldNomeFuncionario.setEnabled(!true);
        jTextFieldNrDeIdentificacao.setEnabled(!true);
        preencherTabela("select * from funcionario order by id");
       } else{
           
        jComboBoxEstadoCivilFuncionario.setEnabled(!true);
        jComboBoxSexoFuncionario.setEnabled(!true);
        jTextFieldContactoFuncionario.setEnabled(!true);
        jTextFieldNascimentoFuncionario.setEnabled(!true);
        jTextFieldNomeFuncionario.setEnabled(!true);
        jTextFieldNrDeIdentificacao.setEnabled(!true);  
        
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);            
        
        mod.setCodigo(Integer.parseInt(jTextFieldId.getText()));
        mod.setNome(jTextFieldNomeFuncionario.getText());
        mod.setContacto(jTextFieldContactoFuncionario.getText());
        mod.setSexo((String)jComboBoxSexoFuncionario.getSelectedItem());
        mod.setNascimento(Integer.valueOf(jTextFieldNascimentoFuncionario.getText()));
        mod.setEstadoCivil((String)jComboBoxEstadoCivilFuncionario.getSelectedItem());
        mod.setNrDeIdentificacao(jTextFieldNrDeIdentificacao.getText());
        control.editar(mod);
        
        jTextFieldNomeFuncionario.setText("");
        jTextFieldContactoFuncionario.setText("");
        jTextFieldNascimentoFuncionario.setText("");
        jTextFieldNrDeIdentificacao.setText("");
        jTextFieldId.setText("");
        
        preencherTabela("select * from funcionario order by id");
       }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        jTextFieldId.setText("");
        jComboBoxEstadoCivilFuncionario.setEnabled(!true);
        jComboBoxSexoFuncionario.setEnabled(!true);
        jTextFieldContactoFuncionario.setEnabled(!true);
        jTextFieldNascimentoFuncionario.setEnabled(!true);
        jTextFieldNomeFuncionario.setEnabled(!true);
        jTextFieldNrDeIdentificacao.setEnabled(!true);        
        
        jTextFieldContactoFuncionario.setText("");
        jTextFieldNascimentoFuncionario.setText("");
        jTextFieldNomeFuncionario.setText("");
        jTextFieldNrDeIdentificacao.setText("");
        
        jButtonCancelar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        
        flag = 1; 
        
        jComboBoxEstadoCivilFuncionario.setEnabled(true);
        jComboBoxSexoFuncionario.setEnabled(true);
        jTextFieldContactoFuncionario.setEnabled(true);
        jTextFieldNascimentoFuncionario.setEnabled(true);
        jTextFieldNomeFuncionario.setEnabled(true);
        jTextFieldNrDeIdentificacao.setEnabled(true);
        
        jTextFieldContactoFuncionario.setText("");
        jTextFieldNascimentoFuncionario.setText("");
        jTextFieldNomeFuncionario.setText("");
        jTextFieldNrDeIdentificacao.setText("");
        
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        
        flag = 2;
        
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        
        jComboBoxEstadoCivilFuncionario.setEnabled(true);
        jComboBoxSexoFuncionario.setEnabled(true);
        jTextFieldContactoFuncionario.setEnabled(true);
        jTextFieldNascimentoFuncionario.setEnabled(true);
        jTextFieldNomeFuncionario.setEnabled(true);
        jTextFieldNrDeIdentificacao.setEnabled(true);

    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        mod.setPesquisa(jTextFieldPesquisar.getText());
        FuncionarioBeans model = control.buscaFuncionario(mod);

        jTextFieldId.setText(String.valueOf(model.getCodigo()));
        jTextFieldNascimentoFuncionario.setText(String.valueOf(model.getNascimento()));
        jTextFieldNomeFuncionario.setText(model.getNome());
        jTextFieldContactoFuncionario.setText(model.getContacto());
        jComboBoxEstadoCivilFuncionario.setSelectedItem(model.getEstadoCivil());
        jComboBoxSexoFuncionario.setSelectedItem(model.getSexo());
        jTextFieldNrDeIdentificacao.setText(model.getNrDeIdentificacao());
        
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        
        jTextFieldId.setEnabled(false);
        jTextFieldNascimentoFuncionario.setEnabled(false);
        jTextFieldNomeFuncionario.setEnabled(false);
        jTextFieldContactoFuncionario.setEnabled(false);
        jComboBoxEstadoCivilFuncionario.setEnabled(false);
        jComboBoxSexoFuncionario.setEnabled(false);
        jTextFieldNrDeIdentificacao.setEnabled(false);
        
        
        jTextFieldId.setText("");
        jTextFieldNascimentoFuncionario.setText("");
        jTextFieldNomeFuncionario.setText("");
        jTextFieldContactoFuncionario.setText("");
        jTextFieldNrDeIdentificacao.setText("");        

        preencherTabela("select * from fornecedor where nomeempresa like '%" + mod.getPesquisa() + "%'");
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
    int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Excluir?");
            if(resposta == JOptionPane.YES_OPTION){
                mod.setCodigo(Integer.parseInt(jTextFieldId.getText()));
                control.excluir(mod);
                
                jTextFieldPesquisar.setText("");
                jTextFieldNomeFuncionario.setText("");
                jTextFieldContactoFuncionario.setText("");
                jTextFieldNascimentoFuncionario.setText("");
                jTextFieldNrDeIdentificacao.setText("");
                jTextFieldId.setText("");
                jButtonEditar.setEnabled(false);
                jButtonExcluir.setEnabled(false);
                
                preencherTabela("select * from funcionario order by id");
            }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionariosMouseClicked
        
        String nome = ""+jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSql("select * from funcionario where nome='"+nome+"'");
            try {
                conex.rs.first();
                jTextFieldId.setText(String.valueOf(conex.rs.getInt("id")));
                jTextFieldNomeFuncionario.setText(String.valueOf(conex.rs.getString("nome")));
                jTextFieldNascimentoFuncionario.setText(String.valueOf(conex.rs.getString("nascimento")));
                jComboBoxSexoFuncionario.setSelectedItem(String.valueOf(conex.rs.getString("sexo")));
                jComboBoxEstadoCivilFuncionario.setSelectedItem(String.valueOf(conex.rs.getString("estadocivil")));
                jTextFieldContactoFuncionario.setText(String.valueOf(conex.rs.getString("contacto")));
                jTextFieldNrDeIdentificacao.setText(String.valueOf(conex.rs.getString("identificacao")));
        
        jButtonExcluir.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        
        jTextFieldNomeFuncionario.setEnabled(false);
        jTextFieldContactoFuncionario.setEnabled(false);
        jTextFieldNascimentoFuncionario.setEnabled(false);
        jTextFieldNrDeIdentificacao.setEnabled(false); 
        jComboBoxEstadoCivilFuncionario.setEnabled(false);
        jComboBoxSexoFuncionario.setEnabled(false);

        preencherTabela("select * from funcionario order by id");
            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(null, "ERRO AO SELECIONAR" +ex);
            }
        conex.desconexao();                                           
    }//GEN-LAST:event_jTableFuncionariosMouseClicked

    
        public void preencherTabela(String sql){
            
        ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"id","Nome","Nascimento","Sexo","Estado Civil","Contacto","Nr De Identificacao"};
        conex.conexao();
        
        conex.executaSql(sql);
            try {
                conex.rs.first();
                do{
                  dados.add(new Object[]{conex.rs.getInt("id"),conex.rs.getString("nome"),conex.rs.getInt("nascimento"),conex.rs.getString("sexo"),conex.rs.getString("estadocivil"),conex.rs.getString("contacto"),conex.rs.getString("identificacao")});  
                }while(conex.rs.next());
            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(null, "ERRO AO PREENCHER ARRAYLIST"+ex);
            }
            
            ModeloTabela modelo = new ModeloTabela(dados, colunas);
            
            jTableFuncionarios.setModel(modelo);
            jTableFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableFuncionarios.getColumnModel().getColumn(0).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(160);
            jTableFuncionarios.getColumnModel().getColumn(1).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(90);
            jTableFuncionarios.getColumnModel().getColumn(2).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(65);
            jTableFuncionarios.getColumnModel().getColumn(3).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableFuncionarios.getColumnModel().getColumn(4).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(5).setPreferredWidth(114);
            jTableFuncionarios.getColumnModel().getColumn(5).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(6).setPreferredWidth(120);
            jTableFuncionarios.getColumnModel().getColumn(6).setResizable(false);
            jTableFuncionarios.getTableHeader().setReorderingAllowed(false);
            jTableFuncionarios.setAutoResizeMode(jTableFuncionarios.AUTO_RESIZE_OFF);
            jTableFuncionarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            conex.desconexao();
        }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFecharCadastroFuncionario;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxEstadoCivilFuncionario;
    private javax.swing.JComboBox<String> jComboBoxSexoFuncionario;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTextField jTextFieldContactoFuncionario;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNascimentoFuncionario;
    private javax.swing.JTextField jTextFieldNomeFuncionario;
    private javax.swing.JTextField jTextFieldNrDeIdentificacao;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
