/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModelBeans.MaterialBeans;
import ModelBeans.ModeloTabela;
import ModelConexao.ConexaoBD;
import ModelDao.MaterialDao;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Aurelio Macie Junior
 */
public class CadastroDeMaterial extends javax.swing.JFrame {
    
    MaterialBeans mod = new MaterialBeans();
    ModelDao.MaterialDao control = new MaterialDao();
    MaterialDao dao = new MaterialDao();
    ConexaoBD conex = new ConexaoBD();
    int flag = 0;
    
    public CadastroDeMaterial() {
        initComponents();
        preencherTabela("select * from material order by material_id");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaterial = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNomeDoMaterial = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jTextFieldValorPorUnidade = new javax.swing.JTextField();
        jButtonPesquisarMaterial = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTableMaterial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMaterialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMaterial);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 270, 700, 140);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Formulário De Cadastro De Material");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 330, 40);

        jTextFieldId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldId.setEnabled(false);
        getContentPane().add(jTextFieldId);
        jTextFieldId.setBounds(90, 70, 40, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("X");
        jButton1.setToolTipText("Fechar Cadastro De Material");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(770, 0, 40, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome Do Material");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 120, 130, 30);

        jTextFieldNomeDoMaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldNomeDoMaterial.setEnabled(false);
        getContentPane().add(jTextFieldNomeDoMaterial);
        jTextFieldNomeDoMaterial.setBounds(200, 120, 240, 30);

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.setToolTipText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(60, 230, 90, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 70, 40, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor Por Unidade");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 170, 130, 30);

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(280, 230, 90, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantidade");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(500, 120, 90, 30);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(500, 230, 90, 25);

        jTextFieldQuantidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldQuantidade.setEnabled(false);
        getContentPane().add(jTextFieldQuantidade);
        jTextFieldQuantidade.setBounds(590, 120, 100, 30);

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(390, 230, 90, 25);

        jTextFieldPesquisar.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(500, 0, 260, 30);

        jTextFieldValorPorUnidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldValorPorUnidade.setEnabled(false);
        getContentPane().add(jTextFieldValorPorUnidade);
        jTextFieldValorPorUnidade.setBounds(200, 170, 80, 30);

        jButtonPesquisarMaterial.setBackground(new java.awt.Color(153, 255, 255));
        jButtonPesquisarMaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPesquisarMaterial.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPesquisarMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/search_24px.png"))); // NOI18N
        jButtonPesquisarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarMaterialActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisarMaterial);
        jButtonPesquisarMaterial.setBounds(460, 0, 40, 30);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(170, 230, 90, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/FundoParaTodasTelasRegistro.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 420);

        setSize(new java.awt.Dimension(824, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        jTextFieldId.setText("");
        jTextFieldNomeDoMaterial.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldValorPorUnidade.setText("");
        
        jTextFieldNomeDoMaterial.setEnabled(false);
        jTextFieldQuantidade.setEnabled(false);
        jTextFieldValorPorUnidade.setEnabled(false);        
        
        jButtonCancelar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonSalvar.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed

        flag = 1; 
        
        //jTextFieldDataDeRegistro.setEnabled(true);
        jTextFieldNomeDoMaterial.setEnabled(true);
        jTextFieldValorPorUnidade.setEnabled(true);
        jTextFieldQuantidade.setEnabled(true);
        
        jTextFieldNomeDoMaterial.setText("");
        jTextFieldValorPorUnidade.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldId.setText("");
        
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       
        jTextFieldPesquisar.setText("");
        if (jTextFieldNomeDoMaterial.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Nome Do Material' Para Continuar!");
           jTextFieldNomeDoMaterial.requestFocus();
       }else if(jTextFieldQuantidade.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Quantidade' Para Continuar!");
           jTextFieldQuantidade.requestFocus();
       }else if(jTextFieldValorPorUnidade.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Valor Por Unidade' Para Continuar!");
           jTextFieldValorPorUnidade.requestFocus();
       /*}else if(jTextFieldDataDeRegistro.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Data De Registro' Para Continuar!");
           jTextFieldDataDeRegistro.requestFocus();*/
       } else if (flag==1){ 

        mod.setNome(jTextFieldNomeDoMaterial.getText());
        mod.setQuantidade(Integer.valueOf(jTextFieldQuantidade.getText()));
        mod.setValor(Float.valueOf(jTextFieldValorPorUnidade.getText()));
        control.salvar(mod);  
            
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        
        jTextFieldNomeDoMaterial.setEnabled(false);
        jTextFieldValorPorUnidade.setEnabled(false);
        jTextFieldQuantidade.setEnabled(false);

        jTextFieldNomeDoMaterial.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldValorPorUnidade.setText("");
        jTextFieldId.setText("");

        preencherTabela("select * from material order by material_id");
        
       } else{
         
        jTextFieldNomeDoMaterial.setEnabled(false);
        jTextFieldValorPorUnidade.setEnabled(false);
        jTextFieldQuantidade.setEnabled(false);           
           
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);            
        
        mod.setCodigo(Integer.parseInt(jTextFieldId.getText()));
        mod.setNome(jTextFieldNomeDoMaterial.getText());
        mod.setQuantidade(Integer.valueOf(jTextFieldQuantidade.getText()));
        mod.setValor(Float.valueOf(jTextFieldValorPorUnidade.getText()));
        control.editar(mod);
        
        jTextFieldNomeDoMaterial.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldValorPorUnidade.setText("");
        jTextFieldId.setText("");
        preencherTabela("select * from material order by material_id");
       }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        
        flag = 2;
        
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        
        jTextFieldNomeDoMaterial.setEnabled(true);
        jTextFieldQuantidade.setEnabled(true);
        jTextFieldValorPorUnidade.setEnabled(true);
        
        
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
    int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Excluir?");
            if(resposta == JOptionPane.YES_OPTION){
                mod.setCodigo(Integer.parseInt(jTextFieldId.getText()));
                control.excluir(mod);
                
                jTextFieldPesquisar.setText("");
                jTextFieldNomeDoMaterial.setText("");
                jTextFieldQuantidade.setText("");
                jTextFieldValorPorUnidade.setText("");
                jTextFieldId.setText("");
                jButtonEditar.setEnabled(false);
                jButtonExcluir.setEnabled(false);
                preencherTabela("select * from material order by material_id");
            }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonPesquisarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarMaterialActionPerformed

        mod.setPesquisa(jTextFieldPesquisar.getText());
        MaterialBeans model = control.buscaMaterial(mod);

        jTextFieldId.setText(String.valueOf(model.getCodigo()));
        jTextFieldNomeDoMaterial.setText(model.getNome());
        jTextFieldQuantidade.setText(String.valueOf(model.getQuantidade()));
        jTextFieldValorPorUnidade.setText(String.valueOf(model.getValor()));
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        
        jTextFieldId.setEnabled(false);
        jTextFieldNomeDoMaterial.setEnabled(false);
        jTextFieldQuantidade.setEnabled(false);
        jTextFieldValorPorUnidade.setEnabled(false);
        
        
        jTextFieldId.setText("");
        jTextFieldNomeDoMaterial.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldValorPorUnidade.setText("");

        preencherTabela("select * from material where material_nome like '%" + mod.getPesquisa() + "%'");
    }//GEN-LAST:event_jButtonPesquisarMaterialActionPerformed

    private void jTableMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMaterialMouseClicked
        
        String nome = ""+jTableMaterial.getValueAt(jTableMaterial.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSql("select * from material where material_nome='"+nome+"'");
            try {
                conex.rs.first();
                jTextFieldId.setText(String.valueOf(conex.rs.getInt("material_id")));
                jTextFieldNomeDoMaterial.setText(String.valueOf(conex.rs.getString("material_nome")));
                jTextFieldQuantidade.setText(String.valueOf(conex.rs.getInt("material_quantidade")));
                jTextFieldValorPorUnidade.setText(String.valueOf(conex.rs.getFloat("material_valor")));
        
        jButtonExcluir.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        
        jTextFieldNomeDoMaterial.setEnabled(false);
        jTextFieldQuantidade.setEnabled(false);
        jTextFieldValorPorUnidade.setEnabled(false);

        preencherTabela("select * from material order by material_id");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERRO AO SELECIONAR" +ex);
            }
        conex.desconexao();                                           
    }//GEN-LAST:event_jTableMaterialMouseClicked

        public void preencherTabela(String sql){
            
        ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"ID","Nome","Quantidade","Valor Por Unidade"};
        conex.conexao();
        
        conex.executaSql(sql);
            try {
                conex.rs.first();
                do{
                  dados.add(new Object[]{conex.rs.getInt("material_id"),conex.rs.getString("material_nome"),conex.rs.getInt("material_quantidade"),conex.rs.getFloat("material_valor")});  
                }while(conex.rs.next());
            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(null, "ERRO AO PREENCHER ARRAYLIST"+ex);
            }
            
            ModeloTabela modelo = new ModeloTabela(dados, colunas);
            
            jTableMaterial.setModel(modelo);
            jTableMaterial.getColumnModel().getColumn(0).setPreferredWidth(79);
            jTableMaterial.getColumnModel().getColumn(0).setResizable(false);
            jTableMaterial.getColumnModel().getColumn(1).setPreferredWidth(205);
            jTableMaterial.getColumnModel().getColumn(1).setResizable(false);
            jTableMaterial.getColumnModel().getColumn(2).setPreferredWidth(205);
            jTableMaterial.getColumnModel().getColumn(2).setResizable(false);
            jTableMaterial.getColumnModel().getColumn(3).setPreferredWidth(205);
            jTableMaterial.getColumnModel().getColumn(3).setResizable(false);
            jTableMaterial.getTableHeader().setReorderingAllowed(false);
            jTableMaterial.setAutoResizeMode(jTableMaterial.AUTO_RESIZE_OFF);
            jTableMaterial.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            conex.desconexao();
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisarMaterial;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMaterial;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNomeDoMaterial;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldValorPorUnidade;
    // End of variables declaration//GEN-END:variables
}
