/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModelConexao.ConexaoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aurelio Macie Junior
 */
public class MenuPrincipal extends javax.swing.JFrame {

    
    ConexaoBD conex = new ConexaoBD();
    CadastroDeUsuarios usuario = new CadastroDeUsuarios();
    CadastroDeClientes cliente = new CadastroDeClientes();
    CadastroDeEntregadores fornecedor = new CadastroDeEntregadores();
    CadastroDeFuncionarios funcionario = new CadastroDeFuncionarios();
    CadastroDeMaterial material = new CadastroDeMaterial();
    StockMaterial stock = new StockMaterial();
    Venda venda = new Venda();
    Info info = new Info();
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(String usuario) {
        initComponents();
        jLabelUsuario.setText(usuario);
        conex.conexao();
    }

    MenuPrincipal() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameMenuPrincipal = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCadastroClientes = new javax.swing.JButton();
        jButtonCadastroFuncionarios = new javax.swing.JButton();
        jButtonCadastroUsuarios = new javax.swing.JButton();
        jButtonCadastroMaterial = new javax.swing.JButton();
        jButtonVenda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonFornecedores = new javax.swing.JButton();
        jButtonFecharFrameInternal = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonAgendamento = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelTelaPrincipal = new javax.swing.JLabel();
        jPanelFundoPrincipal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelNomeDeUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuItemOperarios = new javax.swing.JMenuItem();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemMaterial = new javax.swing.JMenuItem();
        jMenuItemFornecedores = new javax.swing.JMenuItem();
        jMenuMenuPrincipal = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemPaletaSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrameMenuPrincipal.setTitle("Menu Principal");
        jInternalFrameMenuPrincipal.setVisible(true);
        jInternalFrameMenuPrincipal.getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registro De Material E Armazenamento.:");
        jInternalFrameMenuPrincipal.getContentPane().add(jLabel5);
        jLabel5.setBounds(540, 240, 270, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema De Gerenciamento De:");
        jInternalFrameMenuPrincipal.getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 300, 40);

        jButtonCadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/ClintePreto_125px.png"))); // NOI18N
        jButtonCadastroClientes.setToolTipText("Clientes");
        jButtonCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroClientesActionPerformed(evt);
            }
        });
        jInternalFrameMenuPrincipal.getContentPane().add(jButtonCadastroClientes);
        jButtonCadastroClientes.setBounds(370, 70, 130, 130);

        jButtonCadastroFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/worker.png"))); // NOI18N
        jButtonCadastroFuncionarios.setToolTipText("Funcionários(Operários)");
        jButtonCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroFuncionariosActionPerformed(evt);
            }
        });
        jInternalFrameMenuPrincipal.getContentPane().add(jButtonCadastroFuncionarios);
        jButtonCadastroFuncionarios.setBounds(200, 70, 130, 130);

        jButtonCadastroUsuarios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCadastroUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastroUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/icon.png"))); // NOI18N
        jButtonCadastroUsuarios.setToolTipText("Usuários");
        jButtonCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroUsuariosActionPerformed(evt);
            }
        });
        jInternalFrameMenuPrincipal.getContentPane().add(jButtonCadastroUsuarios);
        jButtonCadastroUsuarios.setBounds(30, 70, 130, 130);

        jButtonCadastroMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/RegistroDeMaterial.png"))); // NOI18N
        jButtonCadastroMaterial.setToolTipText("Registro De Material");
        jButtonCadastroMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroMaterialActionPerformed(evt);
            }
        });
        jInternalFrameMenuPrincipal.getContentPane().add(jButtonCadastroMaterial);
        jButtonCadastroMaterial.setBounds(540, 270, 130, 130);

        jButtonVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/shoppingCariinho_cart_125px.png"))); // NOI18N
        jButtonVenda.setToolTipText("Efetuar Venda");
        jButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendaActionPerformed(evt);
            }
        });
        jInternalFrameMenuPrincipal.getContentPane().add(jButtonVenda);
        jButtonVenda.setBounds(30, 270, 130, 130);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastro.:");
        jInternalFrameMenuPrincipal.getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 30, 80, 40);

        jButtonFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/truck_fornecedor.png"))); // NOI18N
        jButtonFornecedores.setToolTipText("Fornecedores");
        jButtonFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFornecedoresActionPerformed(evt);
            }
        });
        jInternalFrameMenuPrincipal.getContentPane().add(jButtonFornecedores);
        jButtonFornecedores.setBounds(540, 70, 130, 130);

        jButtonFecharFrameInternal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonFecharFrameInternal.setText("X");
        jButtonFecharFrameInternal.setToolTipText("Fechar Menu Principal");
        jButtonFecharFrameInternal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharFrameInternalActionPerformed(evt);
            }
        });
        jInternalFrameMenuPrincipal.getContentPane().add(jButtonFecharFrameInternal);
        jButtonFecharFrameInternal.setBounds(900, 0, 39, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/addicionarPrdutoOficial_125px.png"))); // NOI18N
        jButton2.setToolTipText("Adicionar Produto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrameMenuPrincipal.getContentPane().add(jButton2);
        jButton2.setBounds(680, 270, 130, 130);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bloco Operatório.:");
        jInternalFrameMenuPrincipal.getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 240, 120, 20);

        jButtonAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/guide.png"))); // NOI18N
        jButtonAgendamento.setToolTipText("Agendamento");
        jButtonAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendamentoActionPerformed(evt);
            }
        });
        jInternalFrameMenuPrincipal.getContentPane().add(jButtonAgendamento);
        jButtonAgendamento.setBounds(170, 270, 130, 130);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/information_24px.png"))); // NOI18N
        jButton1.setToolTipText("Informação Do Sistema");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrameMenuPrincipal.getContentPane().add(jButton1);
        jButton1.setBounds(910, 370, 30, 30);

        jLabelTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/FundoParaTodasTelasRegistro.jpg"))); // NOI18N
        jInternalFrameMenuPrincipal.getContentPane().add(jLabelTelaPrincipal);
        jLabelTelaPrincipal.setBounds(-6, -1, 970, 410);

        getContentPane().add(jInternalFrameMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 960, 440));

        jPanelFundoPrincipal.setBackground(new java.awt.Color(0, 0, 255));
        jPanelFundoPrincipal.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome De Usuario.:");
        jPanelFundoPrincipal.add(jLabel4);
        jLabel4.setBounds(0, 456, 140, 30);

        jLabelNomeDeUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNomeDeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanelFundoPrincipal.add(jLabelNomeDeUsuario);
        jLabelNomeDeUsuario.setBounds(140, 456, 350, 30);

        getContentPane().add(jPanelFundoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 967, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Usuario Actual.: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 50));

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(0, 51, 255));
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 690, 50));

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuCadastros.setText("| Cadastro |");
        jMenuCadastros.setToolTipText("Cadastros");

        jMenuItemUsuarios.setText("Usuários");
        jMenuItemUsuarios.setToolTipText("Usuários");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemUsuarios);

        jMenuItemOperarios.setText("Operários");
        jMenuItemOperarios.setToolTipText("Operários");
        jMenuItemOperarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOperariosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemOperarios);

        jMenuItemClientes.setText("Clientes");
        jMenuItemClientes.setToolTipText("Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemClientes);

        jMenuItemMaterial.setText("Material");
        jMenuItemMaterial.setToolTipText("Material");
        jMenuItemMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMaterialActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemMaterial);

        jMenuItemFornecedores.setText("Fornecedores");
        jMenuItemFornecedores.setToolTipText("Fornecedores");
        jMenuItemFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedoresActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemFornecedores);

        jMenuBar1.add(jMenuCadastros);

        jMenuMenuPrincipal.setText("Menu-Principal |");
        jMenuMenuPrincipal.setToolTipText("Menu Principal");

        jMenuItem1.setText("Abrir Menu Principal");
        jMenuItem1.setToolTipText("Menu Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuMenuPrincipal.add(jMenuItem1);

        jMenuBar1.add(jMenuMenuPrincipal);

        jMenuSair.setText("Sair |");
        jMenuSair.setToolTipText("Sair");

        jMenuItemPaletaSair.setText("Sair");
        jMenuItemPaletaSair.setToolTipText("Sair Do Sistema");
        jMenuItemPaletaSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPaletaSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemPaletaSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(962, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPaletaSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPaletaSairActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Sair?");
            if(resposta == JOptionPane.YES_OPTION){
        System.exit(0);
            }
    }//GEN-LAST:event_jMenuItemPaletaSairActionPerformed
    
    private void jButtonAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendamentoActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                    //Agendamento a = new Agendamento();
                   //a.setVisible(true);
                   //a.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButtonAgendamentoActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
       
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                   if(usuario==null){
                       usuario = new CadastroDeUsuarios();
                       usuario.setVisible(true);
                       usuario.setResizable(false); 
                   }else{
                       usuario.setVisible(true);
                       usuario.setResizable(false);                         
                   }
                   //CadastroDeUsuarios c1 = new CadastroDeUsuarios();
                   //c1.setVisible(true);
                   //c1.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jMenuItemOperariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOperariosActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                   if(funcionario==null){
                       funcionario = new CadastroDeFuncionarios();
                       funcionario.setVisible(true);
                       funcionario.setResizable(false); 
                   }else{
                       funcionario.setVisible(true);
                       funcionario.setResizable(false);                         
                   }
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jMenuItemOperariosActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
                   if(cliente==null){
                       cliente = new CadastroDeClientes();
                       cliente.setVisible(true);
                       cliente.setResizable(false); 
                   }else{
                       cliente.setVisible(true);
                       cliente.setResizable(false);                         
                   }

        //CadastroDeClientes c1 = new CadastroDeClientes();
        //c1.setVisible(true);
        //c1.setResizable(false);
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMaterialActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                    if(material==null){
                       material = new CadastroDeMaterial();
                       material.setVisible(true);
                       material.setResizable(false); 
                   }else{
                       material.setVisible(true);
                       material.setResizable(false);                         
                   }                   
                    //CadastroDeMaterial c1 = new CadastroDeMaterial();
                    //c1.setVisible(true);
                    //c1.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jMenuItemMaterialActionPerformed

    private void jButtonCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroFuncionariosActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                   if(funcionario==null){
                       funcionario = new CadastroDeFuncionarios();
                       funcionario.setVisible(true);
                       funcionario.setResizable(false); 
                   }else{
                       funcionario.setVisible(true);
                       funcionario.setResizable(false);                         
                   }
                   //CadastroDeUsuarios c1 = new CadastroDeUsuarios();
                   //c1.setVisible(true);
                   //c1.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButtonCadastroFuncionariosActionPerformed

    private void jButtonCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuariosActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                   if(usuario==null){
                       usuario = new CadastroDeUsuarios();
                       usuario.setVisible(true);
                       usuario.setResizable(false); 
                   }else{
                       usuario.setVisible(true);
                       usuario.setResizable(false);                         
                   }
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButtonCadastroUsuariosActionPerformed

    private void jButtonCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroClientesActionPerformed
                   if(cliente==null){
                       cliente = new CadastroDeClientes();
                       cliente.setVisible(true);
                       cliente.setResizable(false); 
                   }else{
                       cliente.setVisible(true);
                       cliente.setResizable(false);                         
                   }

        //CadastroDeClientes c1 = new CadastroDeClientes();
        //c1.setVisible(true);
        //c1.setResizable(false);
    }//GEN-LAST:event_jButtonCadastroClientesActionPerformed

    private void jButtonCadastroMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroMaterialActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                    if(material==null){
                       material = new CadastroDeMaterial();
                       material.setVisible(true);
                       material.setResizable(false); 
                   }else{
                       material.setVisible(true);
                       material.setResizable(false);                         
                   }
                    //CadastroDeMaterial c1 = new CadastroDeMaterial();
                    //c1.setVisible(true);
                    //c1.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButtonCadastroMaterialActionPerformed

    private void jButtonFecharFrameInternalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharFrameInternalActionPerformed
        jInternalFrameMenuPrincipal.dispose();
    }//GEN-LAST:event_jButtonFecharFrameInternalActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jInternalFrameMenuPrincipal.setVisible(true);
//        MenuPrincipal m = new MenuPrincipal();
//        m.setVisible(true);
//        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                    if(material==null){
                       stock = new StockMaterial();
                       stock.setVisible(true);
                       stock.setResizable(false); 
                   }else{
                       stock.setVisible(true);
                       stock.setResizable(false);                         
                   }                    
                    //StockMaterial s = new StockMaterial();
                    //s.setVisible(true);
                    //s.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFornecedoresActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                   if(fornecedor==null){
                       fornecedor = new CadastroDeEntregadores();
                       fornecedor.setVisible(true);
                       fornecedor.setResizable(false); 
                   }else{
                       fornecedor.setVisible(true);
                       fornecedor.setResizable(false);                         
                   }
                    //CadastroDeFornecedores f = new CadastroDeEntregadores();
                    //f.setVisible(true);
                    //f.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButtonFornecedoresActionPerformed

    private void jMenuItemFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedoresActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                   if(fornecedor==null){
                       fornecedor = new CadastroDeEntregadores();
                       fornecedor.setVisible(true);
                       fornecedor.setResizable(false); 
                   }else{
                       fornecedor.setVisible(true);
                       fornecedor.setResizable(false);                         
                   }
                    //CadastroDeFornecedores f = new CadastroDeEntregadores();
                    //f.setVisible(true);
                    //f.setResizable(false);
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }



    }//GEN-LAST:event_jMenuItemFornecedoresActionPerformed

    private void jButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendaActionPerformed
     if(venda==null){
        venda= new Venda();
        venda.setVisible(true);
        venda.setResizable(false);
     }else{
        venda.setVisible(true);
        venda.setResizable(false);
     }
    }//GEN-LAST:event_jButtonVendaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (info==null){
            info = new Info();
            info.setVisible(true);
            info.setResizable(false);
        }else{
            info.setVisible(true);
            info.setResizable(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAgendamento;
    private javax.swing.JButton jButtonCadastroClientes;
    private javax.swing.JButton jButtonCadastroFuncionarios;
    private javax.swing.JButton jButtonCadastroMaterial;
    private javax.swing.JButton jButtonCadastroUsuarios;
    private javax.swing.JButton jButtonFecharFrameInternal;
    private javax.swing.JButton jButtonFornecedores;
    private javax.swing.JButton jButtonVenda;
    private javax.swing.JInternalFrame jInternalFrameMenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelNomeDeUsuario;
    private javax.swing.JLabel jLabelTelaPrincipal;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemFornecedores;
    private javax.swing.JMenuItem jMenuItemMaterial;
    private javax.swing.JMenuItem jMenuItemOperarios;
    private javax.swing.JMenuItem jMenuItemPaletaSair;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuMenuPrincipal;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelFundoPrincipal;
    // End of variables declaration//GEN-END:variables
}
