/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Andela Marrengula
 */
public class Trabalhinho extends javax.swing.JFrame {

    /**
     * Creates new form Trabalhinho
     */
    public Trabalhinho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextFieldContacto = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldSenha = new javax.swing.JTextField();
        jTextFieldConfirmarSenha = new javax.swing.JTextField();
        jButtonEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel1.setText("Nome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 60, 100, 50);

        jLabel2.setText("Email");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 160, 51, 20);

        jLabel3.setText("Contacto");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 250, 80, 20);

        jLabel4.setText("Endereco");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 330, 120, 30);

        jLabel5.setText("Senha");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 390, 130, 40);

        jLabel6.setText("Confirmar Senha");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 460, 140, 40);
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(180, 70, 260, 26);

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(180, 146, 260, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(180, 146, 260, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(180, 146, 260, 30);
        jPanel1.add(jTextFieldContacto);
        jTextFieldContacto.setBounds(180, 246, 270, 30);
        jPanel1.add(jTextFieldEndereco);
        jTextFieldEndereco.setBounds(180, 326, 270, 30);
        jPanel1.add(jTextFieldSenha);
        jTextFieldSenha.setBounds(180, 400, 270, 26);
        jPanel1.add(jTextFieldConfirmarSenha);
        jTextFieldConfirmarSenha.setBounds(180, 470, 270, 26);

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEntrar);
        jButtonEntrar.setBounds(540, 470, 93, 29);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 540));

        setSize(new java.awt.Dimension(762, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
     
        if (jTextFieldNome.getText().isEmpty()){
            jTextFieldNome.setBackground(Color.red);
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Nome' Para Continuar!");
           jTextFieldNome.requestFocus();
       }else if(jTextFieldContacto.getText().isEmpty()){
           jTextFieldContacto.setBackground(Color.red);
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Contacto' Para Continuar!");
           jTextFieldContacto.requestFocus();  
           }else if(jTextFieldEmail.getText().isEmpty()){
               jTextFieldEmail.setBackground(Color.red);
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Email' Para Continuar!");
           jTextFieldEmail.requestFocus(); 
           }else if(jTextFieldEndereco.getText().isEmpty()){
               jTextFieldEndereco.setBackground(Color.red);
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Endereco' Para Continuar!");
           jTextFieldEndereco.requestFocus();
           }else if(jTextFieldSenha.getText().isEmpty()){
               jTextFieldSenha.setBackground(Color.red);
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Senha' Para Continuar!");
           jTextFieldSenha.requestFocus();
           }else if(jTextFieldConfirmarSenha.getText().isEmpty()){
               jTextFieldConfirmarSenha.setBackground(Color.red);
           JOptionPane.showMessageDialog(null, "Preencha O Campo 'Confirmar Senha' Para Continuar!");
           jTextFieldConfirmarSenha.requestFocus();
           
           } else {
           
            JOptionPane.showMessageDialog(null, "Entrou");
           }    
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trabalhinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trabalhinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trabalhinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trabalhinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trabalhinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldConfirmarSenha;
    private javax.swing.JTextField jTextFieldContacto;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSenha;
    // End of variables declaration//GEN-END:variables
}
